version: '2.1'

services:
  flask:
    build:
      context: ./backend
      dockerfile: dockerFlask
    volumes:
      - './backend:/backend'
    ports:
      - 5000:5000
    expose:
      - 5000

    depends_on:
       db: 
          condition: service_healthy

    links:
      - db

  db:
    image: postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - APP_DB_USER=root
      - APP_DB_PASS=root
      - APP_DB_NAME=cai
    volumes:
      - ./backend/db/database:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    expose:
      - 5432
  vue:
    build:
      context: ./frontend
      dockerfile: dockerNuxt
    volumes:
      - './frontend:/frontend'
      - '/frontend/node_modules'
    ports:
      - 8081:8081
    expose: 
      - 8081
    depends_on:
      - flask
