"""fix2

Revision ID: 00f7b1dcb5c4
Revises: d84f34b153c9
Create Date: 2021-12-29 22:53:26.691902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00f7b1dcb5c4'
down_revision = 'd84f34b153c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factura', sa.Column('enviar_factura', sa.Integer(), nullable=True))
    op.add_column('factura', sa.Column('especificar', sa.Text(), nullable=True))
    op.add_column('factura', sa.Column('num_orden', sa.Text(), nullable=True))
    op.add_column('factura', sa.Column('observacion', sa.Text(), nullable=True))
    op.drop_column('factura', 'tipo_pago')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factura', sa.Column('tipo_pago', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('factura', 'observacion')
    op.drop_column('factura', 'num_orden')
    op.drop_column('factura', 'especificar')
    op.drop_column('factura', 'enviar_factura')
    # ### end Alembic commands ###
