"""agregarAtributos

Revision ID: 04184f7ce308
Revises: 6d635e5caca0
Create Date: 2022-01-01 13:18:21.534332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04184f7ce308'
down_revision = '6d635e5caca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacto', sa.Column('descripcion', sa.Text(), nullable=True))
    op.add_column('relator', sa.Column('genero', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relator', 'genero')
    op.drop_column('contacto', 'descripcion')
    # ### end Alembic commands ###
