"""Primera migracion

Revision ID: 078818cec44a
Revises: 
Create Date: 2021-12-19 17:56:31.970659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '078818cec44a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('relator_curso')
    op.drop_table('relator')
   
    op.drop_table('participante_orden')
    op.drop_table('participante_curso')
    op.drop_table('participante_factura')
    op.drop_table('participante')
    op.drop_table('curso')
    
    
    op.drop_table('factura')
    
    
    
    op.drop_table('empresa')
    op.drop_table('orden')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orden',
    sa.Column('id_orden', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sence', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cancelacion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_inicio', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fecha_termino', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_orden', name='orden_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('empresa',
    sa.Column('razon_social', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('giro', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('atencion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('departamento', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rut', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('direccion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('comuna', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('correo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fono', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('razon_social', name='empresa_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('curso',
    sa.Column('sence', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('modalidad', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('categoria', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('horas_curso', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('valor_efectivo_participante', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('valor_imputable_participante', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resolucion_sence', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resolucion_usach', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('f_vigencia', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('sence', name='curso_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('relator',
    sa.Column('rut', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('apellido_paterno', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('apellido_materno', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('titulo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cv', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fecha_nacimiento', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('numero_cuenta', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('banco', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tipo_cuenta', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('rut', name='relator_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('participante',
    sa.Column('rut', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('apellido_paterno', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('apellido_materno', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('genero', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_nacimiento', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('nivel_educacional', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('nacionalidad', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tipo_inscripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ocupacion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('correo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fono', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('razon_social', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['razon_social'], ['empresa.razon_social'], name='FK_participante.razon_social'),
    sa.PrimaryKeyConstraint('rut', name='participante_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('participante_factura',
    sa.Column('rut', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id_factura', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['id_factura'], ['factura.id_factura'], name='FK_participante_orden.id_factura'),
    sa.ForeignKeyConstraint(['rut'], ['participante.rut'], name='FK_participante_orden.rut')
    )
    op.create_table('factura',
    sa.Column('id_factura', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('num_registro', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo_pago', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('num_hes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fecha_emision', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fecha_vencimiento', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_factura', name='factura_pkey')
    )
    op.create_table('relator_curso',
    sa.Column('rut', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sence', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rut'], ['relator.rut'], name='FK_relator_curso.rut'),
    sa.ForeignKeyConstraint(['sence'], ['curso.sence'], name='FK_relator_curso.sence')
    )
    op.create_table('participante_curso',
    sa.Column('rut', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sence', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rut'], ['participante.rut'], name='FK_participante_curso.rut'),
    sa.ForeignKeyConstraint(['sence'], ['curso.sence'], name='FK_participante_curso.sence')
    )
    op.create_table('participante_orden',
    sa.Column('rut', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id_orden', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['id_orden'], ['orden.id_orden'], name='FK_participante_orden.id_orden'),
    sa.ForeignKeyConstraint(['rut'], ['participante.rut'], name='FK_participante_orden.rut')
    )
    # ### end Alembic commands ###
