"""fixcuenta

Revision ID: 12939aabade7
Revises: d55df6d2720c
Create Date: 2022-01-11 22:13:57.254319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12939aabade7'
down_revision = 'd55df6d2720c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cuenta', 'nivel_acceso',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cuenta', 'nivel_acceso',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
