"""borrar_orden

Revision ID: 2bc5c3656406
Revises: 04184f7ce308
Create Date: 2022-01-06 12:16:09.141008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bc5c3656406'
down_revision = '04184f7ce308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('participante_orden')
    op.drop_table('orden')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('participante_orden',
    sa.Column('rut', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id_orden', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_orden'], ['orden.id_orden'], name='participante_orden_id_orden_fkey'),
    sa.ForeignKeyConstraint(['rut'], ['participante.rut'], name='participante_orden_rut_fkey')
    )
    op.create_table('orden',
    sa.Column('id_orden', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('sence', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cancelacion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_inicio', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fecha_termino', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_orden', name='orden_pkey')
    )
    # ### end Alembic commands ###
