"""cambiarrol

Revision ID: 6793c26252a5
Revises: 04fc079610ae
Create Date: 2022-01-07 11:22:59.975494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6793c26252a5'
down_revision = '04fc079610ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
