"""fixTablaFactura

Revision ID: 6d635e5caca0
Revises: 00f7b1dcb5c4
Create Date: 2021-12-29 23:06:17.761641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d635e5caca0'
down_revision = '00f7b1dcb5c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factura', sa.Column('num_cai', sa.Text(), nullable=True))
    op.drop_column('factura', 'num_registro')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factura', sa.Column('num_registro', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('factura', 'num_cai')
    # ### end Alembic commands ###
