"""primeraMigracion

Revision ID: 7b061cfb2b1f
Revises: 078818cec44a
Create Date: 2021-12-19 18:56:19.684661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b061cfb2b1f'
down_revision = '078818cec44a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curso',
    sa.Column('sence', sa.Text(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=True),
    sa.Column('modalidad', sa.Text(), nullable=True),
    sa.Column('categoria', sa.Text(), nullable=True),
    sa.Column('horas_curso', sa.Integer(), nullable=True),
    sa.Column('valor_efectivo_participante', sa.Integer(), nullable=True),
    sa.Column('valor_imputable_participante', sa.Integer(), nullable=True),
    sa.Column('resolucion_sence', sa.Text(), nullable=True),
    sa.Column('resolucion_usach', sa.Text(), nullable=True),
    sa.Column('estado', sa.Text(), nullable=True),
    sa.Column('f_vigencia', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('sence')
    )
    op.create_table('empresa',
    sa.Column('razon_social', sa.Text(), nullable=False),
    sa.Column('giro', sa.Text(), nullable=True),
    sa.Column('atencion', sa.Text(), nullable=True),
    sa.Column('departamento', sa.Text(), nullable=True),
    sa.Column('rut', sa.Text(), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('comuna', sa.Text(), nullable=True),
    sa.Column('correo', sa.Text(), nullable=True),
    sa.Column('fono', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('razon_social')
    )
    op.create_table('factura',
    sa.Column('id_factura', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sence', sa.Text(), nullable=True),
    sa.Column('num_registro', sa.Text(), nullable=True),
    sa.Column('estado', sa.Integer(), nullable=True),
    sa.Column('tipo_pago', sa.Integer(), nullable=True),
    sa.Column('num_hes', sa.Text(), nullable=True),
    sa.Column('fecha_emision', sa.Date(), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id_factura')
    )
    op.create_table('orden',
    sa.Column('id_orden', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sence', sa.Text(), nullable=True),
    sa.Column('cancelacion', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_termino', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id_orden')
    )
    op.create_table('relator',
    sa.Column('rut', sa.Text(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=True),
    sa.Column('apellido_paterno', sa.Text(), nullable=True),
    sa.Column('apellido_materno', sa.Text(), nullable=True),
    sa.Column('titulo', sa.Text(), nullable=True),
    sa.Column('cv', sa.Text(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('numero_cuenta', sa.Text(), nullable=True),
    sa.Column('banco', sa.Text(), nullable=True),
    sa.Column('tipo_cuenta', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('rut')
    )
    op.create_table('instancia',
    sa.Column('id_instancia', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sence', sa.Text(), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('malla', sa.Boolean(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_termino', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['sence'], ['curso.sence'], ),
    sa.PrimaryKeyConstraint('id_instancia')
    )
    op.create_table('participante',
    sa.Column('rut', sa.Text(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=True),
    sa.Column('apellido_paterno', sa.Text(), nullable=True),
    sa.Column('apellido_materno', sa.Text(), nullable=True),
    sa.Column('genero', sa.Integer(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('nivel_educacional', sa.Text(), nullable=True),
    sa.Column('nacionalidad', sa.Text(), nullable=True),
    sa.Column('tipo_inscripcion', sa.Text(), nullable=True),
    sa.Column('ocupacion', sa.Text(), nullable=True),
    sa.Column('correo', sa.Text(), nullable=True),
    sa.Column('fono', sa.Text(), nullable=True),
    sa.Column('razon_social', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['razon_social'], ['empresa.razon_social'], ),
    sa.PrimaryKeyConstraint('rut')
    )
    op.create_table('relator_curso',
    sa.Column('rut', sa.Text(), nullable=False),
    sa.Column('id_instancia', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['id_instancia'], ['factura.id_factura'], ),
    sa.ForeignKeyConstraint(['rut'], ['relator.rut'], ),
    sa.PrimaryKeyConstraint('rut', 'id_instancia')
    )
    op.create_table('participante_curso',
    sa.Column('rut', sa.Text(), nullable=False),
    sa.Column('sence', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['rut'], ['participante.rut'], ),
    sa.ForeignKeyConstraint(['sence'], ['curso.sence'], ),
    sa.PrimaryKeyConstraint('rut', 'sence')
    )
    op.create_table('participante_factura',
    sa.Column('rut', sa.Text(), nullable=False),
    sa.Column('id_factura', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['id_factura'], ['factura.id_factura'], ),
    sa.ForeignKeyConstraint(['rut'], ['participante.rut'], ),
    sa.PrimaryKeyConstraint('rut', 'id_factura')
    )
    op.create_table('participante_orden',
    sa.Column('rut', sa.Text(), nullable=False),
    sa.Column('id_orden', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['id_orden'], ['orden.id_orden'], ),
    sa.ForeignKeyConstraint(['rut'], ['participante.rut'], ),
    sa.PrimaryKeyConstraint('rut', 'id_orden')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participante_orden')
    op.drop_table('participante_factura')
    op.drop_table('participante_curso')
    op.drop_table('relator_curso')
    op.drop_table('participante')
    op.drop_table('instancia')
    op.drop_table('relator')
    op.drop_table('orden')
    op.drop_table('factura')
    op.drop_table('empresa')
    op.drop_table('curso')
    # ### end Alembic commands ###
