"""cambiosreunion0901

Revision ID: d55df6d2720c
Revises: d652c9424e63
Create Date: 2022-01-09 23:25:54.995681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd55df6d2720c'
down_revision = 'd652c9424e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('curso', 'estado')
    op.add_column('factura', sa.Column('id_instancia', sa.Integer(), nullable=True))
    op.add_column('factura', sa.Column('mandada', sa.Boolean(), nullable=False))
    op.add_column('factura', sa.Column('pagada', sa.Boolean(), nullable=False))
    op.add_column('instancia', sa.Column('estado', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instancia', 'estado')
    op.drop_column('factura', 'pagada')
    op.drop_column('factura', 'mandada')
    op.drop_column('factura', 'id_instancia')
    op.add_column('curso', sa.Column('estado', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
