"""cambiarrol2

Revision ID: d652c9424e63
Revises: 6793c26252a5
Create Date: 2022-01-07 11:26:16.868675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd652c9424e63'
down_revision = '6793c26252a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cuenta', sa.Column('nivel_acceso', sa.Integer(), nullable=False))
    op.drop_column('cuenta', 'rol')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

        
    op.add_column('cuenta', sa.Column('rol', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('cuenta', 'nivel_acceso')
    # ### end Alembic commands ###
