"""correccionRelator

Revision ID: d84f34b153c9
Revises: e1a7a7445888
Create Date: 2021-12-24 16:58:12.651558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd84f34b153c9'
down_revision = 'e1a7a7445888'
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	i=0
	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	i=0
	# ### end Alembic commands ###
