"""fix_contacto

Revision ID: e1a7a7445888
Revises: 10dbef3d1d5b
Create Date: 2021-12-24 01:39:44.487263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a7a7445888'
down_revision = '10dbef3d1d5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participante_contacto')
    op.drop_table('empresa_contacto')
    op.drop_table('relator_contacto')
    op.add_column('contacto', sa.Column('razon_social', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'contacto', 'empresa', ['razon_social'], ['razon_social'])
    op.drop_column('empresa', 'correo')
    op.drop_column('empresa', 'fono')
    op.add_column('participante', sa.Column('fono_personal', sa.Text(), nullable=True))
    op.add_column('participante', sa.Column('fono_corporativo', sa.Text(), nullable=True))
    op.add_column('participante', sa.Column('correo_corporativo', sa.Text(), nullable=True))
    op.add_column('participante', sa.Column('correo_personal', sa.Text(), nullable=True))
    op.drop_column('participante', 'correo')
    op.drop_column('participante', 'fono')
    op.add_column('relator', sa.Column('fono_personal', sa.Text(), nullable=True))
    op.add_column('relator', sa.Column('fono_corporativo', sa.Text(), nullable=True))
    op.add_column('relator', sa.Column('correo_corporativo', sa.Text(), nullable=True))
    op.add_column('relator', sa.Column('correo_personal', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relator', 'correo_personal')
    op.drop_column('relator', 'correo_corporativo')
    op.drop_column('relator', 'fono_corporativo')
    op.drop_column('relator', 'fono_personal')
    op.add_column('participante', sa.Column('fono', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('participante', sa.Column('correo', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('participante', 'correo_personal')
    op.drop_column('participante', 'correo_corporativo')
    op.drop_column('participante', 'fono_corporativo')
    op.drop_column('participante', 'fono_personal')


    op.add_column('empresa', sa.Column('fono', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('empresa', sa.Column('correo', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contacto', type_='foreignkey')
    op.drop_column('contacto', 'razon_social')
    op.create_table('relator_contacto',
    sa.Column('rut', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id_contacto', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_contacto'], ['contacto.id_contacto'], name='relator_contacto_id_contacto_fkey'),
    sa.ForeignKeyConstraint(['rut'], ['relator.rut'], name='relator_contacto_rut_fkey')
    )
    op.create_table('empresa_contacto',
    sa.Column('rut', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id_contacto', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_contacto'], ['contacto.id_contacto'], name='empresa_contacto_id_contacto_fkey'),
    sa.ForeignKeyConstraint(['rut'], ['relator.rut'], name='empresa_contacto_rut_fkey')
    )
    op.create_table('participante_contacto',
    sa.Column('rut', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id_contacto', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_contacto'], ['contacto.id_contacto'], name='participante_contacto_id_contacto_fkey'),
    sa.ForeignKeyConstraint(['rut'], ['relator.rut'], name='participante_contacto_rut_fkey')
    )
    # ### end Alembic commands ###
