"""fixTablas

Revision ID: e99d815f6c82
Revises: 7b061cfb2b1f
Create Date: 2021-12-23 13:05:50.251195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e99d815f6c82'
down_revision = '7b061cfb2b1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relator_instancia',
    sa.Column('rut', sa.Text(), nullable=False),
    sa.Column('id_instancia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_instancia'], ['instancia.id_instancia'], ),
    sa.ForeignKeyConstraint(['rut'], ['relator.rut'], ),
    sa.PrimaryKeyConstraint('rut', 'id_instancia')
    )
    op.drop_table('relator_curso')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relator_curso',
    sa.Column('rut', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('id_instancia', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['id_instancia'], ['factura.id_factura'], name='relator_curso_id_instancia_fkey'),
    sa.ForeignKeyConstraint(['rut'], ['relator.rut'], name='relator_curso_rut_fkey'),
    sa.PrimaryKeyConstraint('rut', 'id_instancia', name='relator_curso_pkey')
    )
    op.drop_table('relator_instancia')
    # ### end Alembic commands ###
