"""uniquecorreo

Revision ID: eae72a298161
Revises: 12939aabade7
Create Date: 2022-01-20 19:09:40.395608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eae72a298161'
down_revision = '12939aabade7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cuenta', ['correo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(None, 'cuenta', type_='unique')

    # ### end Alembic commands ###
